# application.yml
spring:
  config:
    import: application-secrets.yml
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url : jdbc:h2:mem:yorijori;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${naver.client-id} # application-secrets.yml에서 불러옴
            client-secret: ${naver.client-secret} # application-secrets.yml에서 불러옴
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: id, name, email, profile_image, birthday, gender, age
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  secretKey: ${jwt.secretKey} # application-secrets.yml에서 불러옴
  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh


